### ISSUE TITLE
1.0.1 showing error

### ISSUE THREAD

**Issue by pksec** [ch-covid-19/self-report-frontend#14]
I am on current master commit:

commit c6c3fa31bdb710275e5a742532ed1672f53bbf8d (HEAD -> master, origin/master, origin/HEAD)
Author: Christian Müller <christian.muller@wifx.net>
Date:   Mon Mar 30 01:18:51 2020 +0200

   v1.0.1

`$ npm run serve`

Logs attached.
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/local/bin/npm', 'run', 'serve' ]
2 info using npm@6.13.4
3 info using node@v8.10.0
4 verbose run-script [ 'preserve', 'serve', 'postserve' ]
5 info lifecycle covid-self-report@1.0.1~preserve: covid-self-report@1.0.1
6 info lifecycle covid-self-report@1.0.1~serve: covid-self-report@1.0.1
7 verbose lifecycle covid-self-report@1.0.1~serve: unsafe-perm in lifecycle true
8 verbose lifecycle covid-self-report@1.0.1~serve: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pksec/india-covid19/self-report-frontend/node_modules/.bin:/home/pksec/perl5/bin:/home/pksec/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/pksec/.local/bin:/home/pksec/software/go/bin
9 verbose lifecycle covid-self-report@1.0.1~serve: CWD: /home/pksec/india-covid19/self-report-frontend
10 silly lifecycle covid-self-report@1.0.1~serve: Args: [ '-c', 'vue-cli-service serve' ]
11 silly lifecycle covid-self-report@1.0.1~serve: Returned: code: 1  signal: null
12 info lifecycle covid-self-report@1.0.1~serve: Failed to exec serve script
13 verbose stack Error: covid-self-report@1.0.1 serve: `vue-cli-service serve`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid covid-self-report@1.0.1
15 verbose cwd /home/pksec/india-covid19/self-report-frontend
16 verbose Linux 5.3.0-42-generic
17 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "run" "serve"
18 verbose node v8.10.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error covid-self-report@1.0.1 serve: `vue-cli-service serve`
22 error Exit status 1
23 error Failed at the covid-self-report@1.0.1 serve script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by mullerch** [comment]
The app should be built/served with yarn. Readme has been updated.
